profile_link=$(readlink "$HOME/.profile")
profile_dir=$(dirname "${profile_link}")
DOTFILES=$(cd "${profile_dir}/.." && pwd)
PROFILEDIR=${PROFILEDIR:-"$DOTFILES/sh/common"}

if test -r /etc/bashrc ; then
	. /etc/bashrc
fi

if test -r "$HOME/.profile.local" ; then
	. "$HOME/.profile.local"
fi

. "${PROFILEDIR}/setup"

if test -r "$HOME/.bashrc.local" ; then
	. "$HOME/.bashrc.local"
fi

. "${PROFILEDIR}/finalise"
