PROFILEDIR=${PROFILEDIR:-"$HOME/.dotfiles/sh/common"}

if test -r /etc/bashrc ; then
	. /etc/bashrc
fi

if test -r "$HOME/.profile.local" ; then
	. "$HOME/.profile.local"
fi

. "${PROFILEDIR}/setup"

if test -r "$HOME/.bashrc.local" ; then
	. "$HOME/.bashrc.local"
fi

. "${PROFILEDIR}/finalise"
