# If you take a copy of this file and customise it, be sure to set $DOTFILES
# (and $PROFILEDIR), source $PROFILEDIR/setup, and call profile_finalise

shell_name=ksh
profile_link=$(readlink "$HOME/.kshrc")
profile_dir=$(dirname "${profile_link}")
DOTFILES=$(cd "${profile_dir}/../.." && pwd)
PROFILEDIR=${PROFILEDIR:-"$DOTFILES/sh/common"}

if test -r /etc/kshrc ; then
	. /etc/kshrc
fi

. "${PROFILEDIR}/setup"

if test -r "$HOME/.kshrc.local" ; then
	. "$HOME/.kshrc.local"
fi

profile_finalise

