#! /bin/sh

set -x

launchctl stop com.apple.syncdefaultsd
killall cfprefsd

defaults import NSGlobalDomain NSGlobalDomain.plist
defaults import com.apple.terminal com.apple.Terminal.plist
defaults import com.apple.dock com.apple.dock.plist
defaults import com.apple.Finder com.apple.Finder.plist
defaults import com.apple.desktopservices com.apple.desktopservices.plist

defaults delete com.apple.dock no-bouncing 2>/dev/null

launchctl start com.apple.syncdefaultsd

killall cfprefsd
killall Dock
killall Finder
killall SystemUIServer
killall Terminal


