#! /bin/sh

set -x

defaults write NSGlobalDomain AppleAquaColorVariant -int 6
defaults write NSGlobalDomain AppleHighlightColor "0.500000 0.500000 0.500000"
defaults write NSGlobalDomain NSTableViewDefaultSizeMode -int 1
defaults write NSGlobalDomain AppleShowScrollBars "automatic"
defaults write NSGlobalDomain AppleScrollAnimationEnabled -bool YES
defaults write NSGlobalDomain NSCloseAlwaysConfirmsChanges -bool YES
defaults write NSGlobalDomain NSQuitAlwaysKeepsWindows -bool YES
defaults write NSGlobalDomain AppleAntiAliasingThreshold -int 4
defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool NO
defaults write NSGlobalDomain AppleEnableMenuBarTransparency -bool YES
defaults write NSGlobalDomain AppleMiniaturizeOnDoubleClick -bool NO
defaults write NSGlobalDomain AppleSpacesSwitchOnActivate -bool YES
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool NO
defaults write NSGlobalDomain WebAutomaticSpellingCorrectionEnabled -bool NO
defaults write NSGlobalDomain NSSpellCheckerAutomaticallyIdentifiesLanguages -bool YES
defaults write NSGlobalDomain AppleKeyboardUIMode -int 2
defaults write NSGlobalDomain AppleUserLanguages -int 2
defaults write NSGlobalDomain AppleLanguages -array "en-GB" "en"
defaults write NSGlobalDomain NSPreferredSpellServerLanguage "en_GB"
defaults write NSGlobalDomain NSPreferredSpellServerVendors -dict "en_GB" "Apple"
defaults write NSGlobalDomain AppleLocale "en_GB"
defaults write NSGlobalDomain AppleMeasurementUnits "Centimetres"
defaults write NSGlobalDomain AppleCollationOrder "root"
defaults write NSGlobalDomain AppleICUNumberSymbols -dict "1" ""
defaults write NSGlobalDomain AppleICUDateFormatStrings -dict "1" "yyyy-MM-dd" "2" "yyyy-MMM-dd" "3" "EEE d MMMM y"
defaults write NSGlobalDomain AppleMetricUnits -bool YES

#defaults import com.apple.terminal com.apple.Terminal.plist

defaults delete com.apple.dock no-bouncing 2>/dev/null
defaults write com.apple.dock autohide -bool NO
defaults write com.apple.dock dashboard-in-overlay -bool YES
defaults write com.apple.dock expose-group-by-app -bool YES
defaults write com.apple.dock magnification -int 0
defaults write com.apple.dock mineffect "suck"
defaults write com.apple.dock minimize-to-application -bool NO
defaults write com.apple.dock orientation "bottom"
defaults write com.apple.dock pinning "middle"
defaults write com.apple.dock show-process-indicators -bool YES
defaults write com.apple.dock showhidden -bool YES

defaults write com.apple.Finder ShowPathBar -bool YES

defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool NO

defaults write com.apple.mail NSPreferredMailCharset "UTF-8"

killall cfprefsd
killall Dock
killall Finder
killall SystemUIServer


