# ~/.zshenv is processed for every shell, immediately after /etc/zshenv

# /etc/zshenv
# ~/.zshenv
# /etc/zprofile (login only)
# ~/.zprofile   (login only)
# /etc/zshrc    (interactive only)
# ~/.zshrc      (interactive only)
# /etc/zlogin   (login only)
# ~/.zlogin     (login only)

profile_link=$(readlink "$HOME/.profile")
profile_dir=$(dirname ${profile_link})
DOTFILES=$(cd ${profile_dir}/.. && pwd)
PROFILEDIR=${PROFILEDIR:-"$DOTFILES/sh/common"}

if test -r "$HOME/.zshenv.local" ; then
	. "$HOME/.zshenv.local"
fi

. "${PROFILEDIR}/setup"
